# Generated by Django 3.2.7 on 2021-09-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
